LOGISTIC REGRESSION(MULTICLASS)

STEP 1: IMPORT IMPORTANT LIBRARIES

In [3]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import confusion_matrix


STEP 2: IMPORT AND READ DATA

In [5]:
df=pd.read_csv('Iris.csv')

In [6]:
X=df.iloc[:,1:5]
Y=df.iloc[:,5]

STEP 3: EXPLORATORY DATA ANALYSIS

In [7]:
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [8]:
Y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [10]:
X.shape

(150, 4)

In [11]:
Y.shape

(150,)

In [12]:
X.describe(),Y.describe()

(       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
 count     150.000000    150.000000     150.000000    150.000000
 mean        5.843333      3.054000       3.758667      1.198667
 std         0.828066      0.433594       1.764420      0.763161
 min         4.300000      2.000000       1.000000      0.100000
 25%         5.100000      2.800000       1.600000      0.300000
 50%         5.800000      3.000000       4.350000      1.300000
 75%         6.400000      3.300000       5.100000      1.800000
 max         7.900000      4.400000       6.900000      2.500000,
 count             150
 unique              3
 top       Iris-setosa
 freq               50
 Name: Species, dtype: object)

In [13]:
X.info(),Y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB
<class 'pandas.core.series.Series'>
RangeIndex: 150 entries, 0 to 149
Series name: Species
Non-Null Count  Dtype 
--------------  ----- 
150 non-null    object
dtypes: object(1)
memory usage: 1.3+ KB


(None, None)

STEP 4: TRAIN-TEST SPLIT

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25)

STEP 5: CREATING OBJECT FOR MODEL

In [15]:
lgr=LogisticRegression()
lgr.fit(X_train,Y_train)

LogisticRegression()

In [16]:
print(lgr.score(X_train,Y_train))
print(lgr.coef_)
print(lgr.intercept_)

0.9732142857142857
[[-0.40610826  0.90069696 -2.28691194 -0.97079523]
 [ 0.25513028 -0.34861042 -0.10028195 -0.83698659]
 [ 0.15097798 -0.55208655  2.38719389  1.80778182]]
[  8.95045008   3.17936473 -12.1298148 ]


STEP 6: PREDICTION

In [17]:
y_pred=lgr.predict(X_test)

In [18]:
confusion_matrix(Y_test,y_pred)

array([[15,  0,  0],
       [ 0, 13,  0],
       [ 0,  1,  9]])

In [19]:
print(lgr.predict([[6.3,3.2,4.3,0.1]]))

['Iris-versicolor']


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


STEP 7: EVALUATION

In [20]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.93      1.00      0.96        13
 Iris-virginica       1.00      0.90      0.95        10

       accuracy                           0.97        38
      macro avg       0.98      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38

